export const monedas=[
    {
      "soporte_moneda_id": "1",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "MXN",
      "soporte_moneda_nombre": "Peso Mexicano",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "peso",
      "soporte_moneda_nombre_plural": "pesos",
      "soporte_moneda_denominacion": "M.N.",
      "soporte_moneda_simbolo": "$",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "2",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "USD",
      "soporte_moneda_nombre": "Dolar americano",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "dolar de los E.U.A.",
      "soporte_moneda_nombre_plural": "dólares de los E.U.A.",
      "soporte_moneda_denominacion": "M.E.",
      "soporte_moneda_simbolo": "US$",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "3",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "EUR",
      "soporte_moneda_nombre": "Euro",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "euro",
      "soporte_moneda_nombre_plural": "euros",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "EUR",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "4",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "AMD",
      "soporte_moneda_nombre": "Dram armenio",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "5",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "ANG",
      "soporte_moneda_nombre": "Florín antillano neerlandés",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "6",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "AOA",
      "soporte_moneda_nombre": "Kwanza",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "7",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "ARS",
      "soporte_moneda_nombre": "Peso Argentino",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "8",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "AUD",
      "soporte_moneda_nombre": "Dólar Australiano",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "9",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "AWG",
      "soporte_moneda_nombre": "Aruba Florin",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "10",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "AZN",
      "soporte_moneda_nombre": "Azerbaijanian Manat",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "11",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "BAM",
      "soporte_moneda_nombre": "Convertibles marca",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "12",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "BBD",
      "soporte_moneda_nombre": "Dólar de Barbados",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "13",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "BDT",
      "soporte_moneda_nombre": "Taka",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "14",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "BGN",
      "soporte_moneda_nombre": "Lev búlgaro",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "15",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "BHD",
      "soporte_moneda_nombre": "Dinar de Bahrein",
      "soporte_moneda_decimales": "3",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "16",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "BIF",
      "soporte_moneda_nombre": "Burundi Franc",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "17",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "BMD",
      "soporte_moneda_nombre": "Dólar de Bermudas",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "18",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "BND",
      "soporte_moneda_nombre": "Dólar de Brunei",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "19",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "BOB",
      "soporte_moneda_nombre": "Boliviano",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "20",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "BOV",
      "soporte_moneda_nombre": "Mvdol",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "21",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "BRL",
      "soporte_moneda_nombre": "Real brasileño",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "22",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "BSD",
      "soporte_moneda_nombre": "Dólar de las Bahamas",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "23",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "BTN",
      "soporte_moneda_nombre": "Ngultrum",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "24",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "BWP",
      "soporte_moneda_nombre": "Pula",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "25",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "BYR",
      "soporte_moneda_nombre": "Rublo bielorruso",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "26",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "BZD",
      "soporte_moneda_nombre": "Dólar de Belice",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "27",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "CAD",
      "soporte_moneda_nombre": "Dolar Canadiense",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "28",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "CDF",
      "soporte_moneda_nombre": "Franco congoleño",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "29",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "CHE",
      "soporte_moneda_nombre": "WIR Euro",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "30",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "CHF",
      "soporte_moneda_nombre": "Franco Suizo",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "31",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "CHW",
      "soporte_moneda_nombre": "Franc WIR",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "32",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "CLF",
      "soporte_moneda_nombre": "Unidad de Fomento",
      "soporte_moneda_decimales": "4",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "33",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "CLP",
      "soporte_moneda_nombre": "Peso chileno",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "34",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "CNY",
      "soporte_moneda_nombre": "Yuan Renminbi",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "35",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "COP",
      "soporte_moneda_nombre": "Peso Colombiano",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "36",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "COU",
      "soporte_moneda_nombre": "Unidad de Valor real",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "37",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "CRC",
      "soporte_moneda_nombre": "Colón costarricense",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "38",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "CUC",
      "soporte_moneda_nombre": "Peso Convertible",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "39",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "CUP",
      "soporte_moneda_nombre": "Peso Cubano",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "40",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "CVE",
      "soporte_moneda_nombre": "Cabo Verde Escudo",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "41",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "CZK",
      "soporte_moneda_nombre": "Corona checa",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "42",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "DJF",
      "soporte_moneda_nombre": "Franco de Djibouti",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "43",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "DKK",
      "soporte_moneda_nombre": "Corona danesa",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "44",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "DOP",
      "soporte_moneda_nombre": "Peso Dominicano",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "45",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "DZD",
      "soporte_moneda_nombre": "Dinar argelino",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "46",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "EGP",
      "soporte_moneda_nombre": "Libra egipcia",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "47",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "ERN",
      "soporte_moneda_nombre": "Nakfa",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "48",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "ETB",
      "soporte_moneda_nombre": "Birr etíope",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "49",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "ALL",
      "soporte_moneda_nombre": "Lek",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "50",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "FJD",
      "soporte_moneda_nombre": "Dólar de Fiji",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "51",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "FKP",
      "soporte_moneda_nombre": "Libra malvinense",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "52",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "GBP",
      "soporte_moneda_nombre": "Libra Esterlina",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "53",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "GEL",
      "soporte_moneda_nombre": "Lari",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "54",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "GHS",
      "soporte_moneda_nombre": "Cedi de Ghana",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "55",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "GIP",
      "soporte_moneda_nombre": "Libra de Gibraltar",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "56",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "GMD",
      "soporte_moneda_nombre": "Dalasi",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "57",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "GNF",
      "soporte_moneda_nombre": "Franco guineano",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "58",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "GTQ",
      "soporte_moneda_nombre": "Quetzal",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "59",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "GYD",
      "soporte_moneda_nombre": "Dólar guyanés",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "60",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "HKD",
      "soporte_moneda_nombre": "Dolar De Hong Kong",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "61",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "HNL",
      "soporte_moneda_nombre": "Lempira",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "62",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "HRK",
      "soporte_moneda_nombre": "Kuna",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "63",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "HTG",
      "soporte_moneda_nombre": "Gourde",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "64",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "HUF",
      "soporte_moneda_nombre": "Florín",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "65",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "IDR",
      "soporte_moneda_nombre": "Rupia",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "66",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "ILS",
      "soporte_moneda_nombre": "Nuevo Shekel Israelí",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "67",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "INR",
      "soporte_moneda_nombre": "Rupia india",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "68",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "IQD",
      "soporte_moneda_nombre": "Dinar iraquí",
      "soporte_moneda_decimales": "3",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "69",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "IRR",
      "soporte_moneda_nombre": "Rial iraní",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "70",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "ISK",
      "soporte_moneda_nombre": "Corona islandesa",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "71",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "JMD",
      "soporte_moneda_nombre": "Dólar Jamaiquino",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "72",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "JOD",
      "soporte_moneda_nombre": "Dinar jordano",
      "soporte_moneda_decimales": "3",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "73",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "JPY",
      "soporte_moneda_nombre": "Yen",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "74",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "KES",
      "soporte_moneda_nombre": "Chelín keniano",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "75",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "KGS",
      "soporte_moneda_nombre": "Som",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "76",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "KHR",
      "soporte_moneda_nombre": "Riel",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "77",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "KMF",
      "soporte_moneda_nombre": "Franco Comoro",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "78",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "KPW",
      "soporte_moneda_nombre": "Corea del Norte ganó",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "79",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "KRW",
      "soporte_moneda_nombre": "Won",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "80",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "KWD",
      "soporte_moneda_nombre": "Dinar kuwaití",
      "soporte_moneda_decimales": "3",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "81",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "KYD",
      "soporte_moneda_nombre": "Dólar de las Islas Caimán",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "82",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "KZT",
      "soporte_moneda_nombre": "Tenge",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "83",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "LAK",
      "soporte_moneda_nombre": "Kip",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "84",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "LBP",
      "soporte_moneda_nombre": "Libra libanesa",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "85",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "LKR",
      "soporte_moneda_nombre": "Rupia de Sri Lanka",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "86",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "LRD",
      "soporte_moneda_nombre": "Dólar liberiano",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "87",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "LSL",
      "soporte_moneda_nombre": "Loti",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "88",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "LYD",
      "soporte_moneda_nombre": "Dinar libio",
      "soporte_moneda_decimales": "3",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "89",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "MAD",
      "soporte_moneda_nombre": "Dirham marroquí",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "90",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "MDL",
      "soporte_moneda_nombre": "Leu moldavo",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "91",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "MGA",
      "soporte_moneda_nombre": "Ariary malgache",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "92",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "MKD",
      "soporte_moneda_nombre": "Denar",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "93",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "MMK",
      "soporte_moneda_nombre": "Kyat",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "94",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "MNT",
      "soporte_moneda_nombre": "Tugrik",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "95",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "MOP",
      "soporte_moneda_nombre": "Pataca",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "96",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "MRO",
      "soporte_moneda_nombre": "Ouguiya",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "97",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "MUR",
      "soporte_moneda_nombre": "Rupia de Mauricio",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "98",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "MVR",
      "soporte_moneda_nombre": "Rupia",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "99",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "MWK",
      "soporte_moneda_nombre": "Kwacha",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "100",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "AED",
      "soporte_moneda_nombre": "Dirham de EAU",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "101",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "MXV",
      "soporte_moneda_nombre": "México Unidad de Inversión (UDI)",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "102",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "MYR",
      "soporte_moneda_nombre": "Ringgit malayo",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "103",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "MZN",
      "soporte_moneda_nombre": "Mozambique Metical",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "104",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "NAD",
      "soporte_moneda_nombre": "Dólar de Namibia",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "105",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "NGN",
      "soporte_moneda_nombre": "Naira",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "106",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "NIO",
      "soporte_moneda_nombre": "Córdoba Oro",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "107",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "NOK",
      "soporte_moneda_nombre": "Corona noruega",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "108",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "NPR",
      "soporte_moneda_nombre": "Rupia nepalí",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "109",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "NZD",
      "soporte_moneda_nombre": "Dólar de Nueva Zelanda",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "110",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "OMR",
      "soporte_moneda_nombre": "Rial omaní",
      "soporte_moneda_decimales": "3",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "111",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "PAB",
      "soporte_moneda_nombre": "Balboa",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "112",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "PEN",
      "soporte_moneda_nombre": "Nuevo Sol",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "113",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "PGK",
      "soporte_moneda_nombre": "Kina",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "114",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "PHP",
      "soporte_moneda_nombre": "Peso filipino",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "115",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "PKR",
      "soporte_moneda_nombre": "Rupia de Pakistán",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "116",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "PLN",
      "soporte_moneda_nombre": "Zloty",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "117",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "PYG",
      "soporte_moneda_nombre": "Guaraní",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "118",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "QAR",
      "soporte_moneda_nombre": "Qatar Rial",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "119",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "RON",
      "soporte_moneda_nombre": "Leu rumano",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "120",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "RSD",
      "soporte_moneda_nombre": "Dinar serbio",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "121",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "RUB",
      "soporte_moneda_nombre": "Rublo ruso",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "122",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "RWF",
      "soporte_moneda_nombre": "Franco ruandés",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "123",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "SAR",
      "soporte_moneda_nombre": "Riyal saudí",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "124",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "SBD",
      "soporte_moneda_nombre": "Dólar de las Islas Salomón",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "125",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "SCR",
      "soporte_moneda_nombre": "Rupia de Seychelles",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "126",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "SDG",
      "soporte_moneda_nombre": "Libra sudanesa",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "127",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "SEK",
      "soporte_moneda_nombre": "Corona sueca",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "128",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "SGD",
      "soporte_moneda_nombre": "Dolar De Singapur",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "129",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "SHP",
      "soporte_moneda_nombre": "Libra de Santa Helena",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "130",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "SLL",
      "soporte_moneda_nombre": "Leona",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "131",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "SOS",
      "soporte_moneda_nombre": "Chelín somalí",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "132",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "SRD",
      "soporte_moneda_nombre": "Dólar de Suriname",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "133",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "SSP",
      "soporte_moneda_nombre": "Libra sudanesa Sur",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "134",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "STD",
      "soporte_moneda_nombre": "Dobra",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "135",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "SVC",
      "soporte_moneda_nombre": "Colon El Salvador",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "136",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "SYP",
      "soporte_moneda_nombre": "Libra Siria",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "137",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "SZL",
      "soporte_moneda_nombre": "Lilangeni",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "138",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "THB",
      "soporte_moneda_nombre": "Baht",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "139",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "TJS",
      "soporte_moneda_nombre": "Somoni",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "140",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "TMT",
      "soporte_moneda_nombre": "Turkmenistán nuevo manat",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "141",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "TND",
      "soporte_moneda_nombre": "Dinar tunecino",
      "soporte_moneda_decimales": "3",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "142",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "TOP",
      "soporte_moneda_nombre": "Pa'anga",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "143",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "TRY",
      "soporte_moneda_nombre": "Lira turca",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "144",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "TTD",
      "soporte_moneda_nombre": "Dólar de Trinidad y Tobago",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "145",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "TWD",
      "soporte_moneda_nombre": "Nuevo dólar de Taiwán",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "146",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "TZS",
      "soporte_moneda_nombre": "Shilling tanzano",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "147",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "UAH",
      "soporte_moneda_nombre": "Hryvnia",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "148",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "UGX",
      "soporte_moneda_nombre": "Shilling de Uganda",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "149",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "AFN",
      "soporte_moneda_nombre": "Afghani",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "150",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "USN",
      "soporte_moneda_nombre": "Dólar estadounidense (día siguiente)",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "151",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "UYI",
      "soporte_moneda_nombre": "Peso Uruguay en Unidades Indexadas (URUIURUI)",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "152",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "UYU",
      "soporte_moneda_nombre": "Peso Uruguayo",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "153",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "UZS",
      "soporte_moneda_nombre": "Uzbekistán Sum",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "154",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "VEF",
      "soporte_moneda_nombre": "Bolívar",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "155",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "VND",
      "soporte_moneda_nombre": "Dong",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "156",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "VUV",
      "soporte_moneda_nombre": "Vatu",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "157",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "WST",
      "soporte_moneda_nombre": "Tala",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "158",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "XAF",
      "soporte_moneda_nombre": "Franco CFA BEAC",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "159",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "XAG",
      "soporte_moneda_nombre": "Plata",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "160",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "XAU",
      "soporte_moneda_nombre": "Oro",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "161",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "XBA",
      "soporte_moneda_nombre": "Unidad de Mercados de Bonos Unidad Europea Composite (EURCO)",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "162",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "XBB",
      "soporte_moneda_nombre": "Unidad Monetaria de Bonos de Mercados Unidad Europea (UEM-6)",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "163",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "XBC",
      "soporte_moneda_nombre": "Mercados de Bonos Unidad Europea unidad de cuenta a 9 (UCE-9)",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "164",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "XBD",
      "soporte_moneda_nombre": "Mercados de Bonos Unidad Europea unidad de cuenta a 17 (UCE-17)",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "165",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "XCD",
      "soporte_moneda_nombre": "Dólar del Caribe Oriental",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "166",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "XDR",
      "soporte_moneda_nombre": "DEG (Derechos Especiales de Giro)",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "167",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "XOF",
      "soporte_moneda_nombre": "Franco CFA BCEAO",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "168",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "XPD",
      "soporte_moneda_nombre": "Paladio",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "169",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "XPF",
      "soporte_moneda_nombre": "Franco CFP",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "170",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "XPT",
      "soporte_moneda_nombre": "Platino",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "171",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "XSU",
      "soporte_moneda_nombre": "Sucre",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "172",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "XTS",
      "soporte_moneda_nombre": "Códigos reservados específicamente para propósitos de prueba",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "0",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "173",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "XUA",
      "soporte_moneda_nombre": "Unidad ADB de Cuenta",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "174",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "XXX",
      "soporte_moneda_nombre": "Los códigos asignados para las transacciones en que intervenga ninguna moneda",
      "soporte_moneda_decimales": "0",
      "soporte_moneda_porcentaje_variacion": "0",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "175",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "YER",
      "soporte_moneda_nombre": "Rial yemení",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "176",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "ZAR",
      "soporte_moneda_nombre": "Rand",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "177",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "ZMW",
      "soporte_moneda_nombre": "Kwacha zambiano",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    },
    {
      "soporte_moneda_id": "178",
      "soporte_idioma_id": "1",
      "soporte_moneda_clave": "ZWL",
      "soporte_moneda_nombre": "Zimbabwe Dólar",
      "soporte_moneda_decimales": "2",
      "soporte_moneda_porcentaje_variacion": "5",
      "soporte_moneda_nombre_singular": "",
      "soporte_moneda_nombre_plural": "",
      "soporte_moneda_denominacion": "",
      "soporte_moneda_simbolo": "",
      "soporte_moneda_status": "A"
    }
    ]